# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"\x0e\n\x0c\x45mptyMessage\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc4\x01\n\x08Registry\x12&\n\x08register\x12\x08.Message\x1a\x10.MessageResponse\x12(\n\nderegister\x12\x08.Message\x1a\x10.MessageResponse\x12\x33\n\x15populate_finger_table\x12\x08.Message\x1a\x10.MessageResponse\x12\x31\n\x0eget_chord_info\x12\r.EmptyMessage\x1a\x10.MessageResponse2\x82\x02\n\x04Node\x12\x33\n\x10get_finger_table\x12\r.EmptyMessage\x1a\x10.MessageResponse\x12\"\n\x04save\x12\x08.Message\x1a\x10.MessageResponse\x12$\n\x06remove\x12\x08.Message\x1a\x10.MessageResponse\x12\"\n\x04\x66ind\x12\x08.Message\x1a\x10.MessageResponse\x12\'\n\x04quit\x12\r.EmptyMessage\x1a\x10.MessageResponse\x12.\n\x0bget_node_id\x12\r.EmptyMessage\x1a\x10.MessageResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=15
  _EMPTYMESSAGE._serialized_end=29
  _MESSAGE._serialized_start=31
  _MESSAGE._serialized_end=57
  _MESSAGERESPONSE._serialized_start=59
  _MESSAGERESPONSE._serialized_end=111
  _REGISTRY._serialized_start=114
  _REGISTRY._serialized_end=310
  _NODE._serialized_start=313
  _NODE._serialized_end=571
# @@protoc_insertion_point(module_scope)
