# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SimpleService.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xbf\x01\n\rSimpleService\x12/\n\x11GetServerResponse\x12\x08.Message\x1a\x10.MessageResponse\x12+\n\rReverseString\x12\x08.Message\x1a\x10.MessageResponse\x12)\n\x0bSplitString\x12\x08.Message\x1a\x10.MessageResponse\x12%\n\x07IsPrime\x12\x08.Message\x1a\x10.MessageResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimpleService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=23
  _MESSAGE._serialized_end=49
  _MESSAGERESPONSE._serialized_start=51
  _MESSAGERESPONSE._serialized_end=103
  _SIMPLESERVICE._serialized_start=106
  _SIMPLESERVICE._serialized_end=297
# @@protoc_insertion_point(module_scope)
