# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SimpleService_pb2 as SimpleService__pb2


class SimpleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponse = channel.unary_unary(
                '/SimpleService/GetServerResponse',
                request_serializer=SimpleService__pb2.Message.SerializeToString,
                response_deserializer=SimpleService__pb2.MessageResponse.FromString,
                )
        self.ReverseString = channel.unary_unary(
                '/SimpleService/ReverseString',
                request_serializer=SimpleService__pb2.Message.SerializeToString,
                response_deserializer=SimpleService__pb2.MessageResponse.FromString,
                )
        self.SplitString = channel.unary_unary(
                '/SimpleService/SplitString',
                request_serializer=SimpleService__pb2.Message.SerializeToString,
                response_deserializer=SimpleService__pb2.MessageResponse.FromString,
                )
        self.IsPrime = channel.unary_unary(
                '/SimpleService/IsPrime',
                request_serializer=SimpleService__pb2.Message.SerializeToString,
                response_deserializer=SimpleService__pb2.MessageResponse.FromString,
                )


class SimpleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsPrime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponse,
                    request_deserializer=SimpleService__pb2.Message.FromString,
                    response_serializer=SimpleService__pb2.MessageResponse.SerializeToString,
            ),
            'ReverseString': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseString,
                    request_deserializer=SimpleService__pb2.Message.FromString,
                    response_serializer=SimpleService__pb2.MessageResponse.SerializeToString,
            ),
            'SplitString': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitString,
                    request_deserializer=SimpleService__pb2.Message.FromString,
                    response_serializer=SimpleService__pb2.MessageResponse.SerializeToString,
            ),
            'IsPrime': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPrime,
                    request_deserializer=SimpleService__pb2.Message.FromString,
                    response_serializer=SimpleService__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimpleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleService/GetServerResponse',
            SimpleService__pb2.Message.SerializeToString,
            SimpleService__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReverseString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleService/ReverseString',
            SimpleService__pb2.Message.SerializeToString,
            SimpleService__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SplitString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleService/SplitString',
            SimpleService__pb2.Message.SerializeToString,
            SimpleService__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleService/IsPrime',
            SimpleService__pb2.Message.SerializeToString,
            SimpleService__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
