# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import queue_pb2 as queue__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.unary_unary(
                '/Server/put',
                request_serializer=queue__pb2.Message.SerializeToString,
                response_deserializer=queue__pb2.MessageResponse.FromString,
                )
        self.peek = channel.unary_unary(
                '/Server/peek',
                request_serializer=queue__pb2.EmptyMessage.SerializeToString,
                response_deserializer=queue__pb2.MessageResponse.FromString,
                )
        self.pop = channel.unary_unary(
                '/Server/pop',
                request_serializer=queue__pb2.EmptyMessage.SerializeToString,
                response_deserializer=queue__pb2.MessageResponse.FromString,
                )
        self.size = channel.unary_unary(
                '/Server/size',
                request_serializer=queue__pb2.EmptyMessage.SerializeToString,
                response_deserializer=queue__pb2.MessageResponse.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def peek(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def size(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=queue__pb2.Message.FromString,
                    response_serializer=queue__pb2.MessageResponse.SerializeToString,
            ),
            'peek': grpc.unary_unary_rpc_method_handler(
                    servicer.peek,
                    request_deserializer=queue__pb2.EmptyMessage.FromString,
                    response_serializer=queue__pb2.MessageResponse.SerializeToString,
            ),
            'pop': grpc.unary_unary_rpc_method_handler(
                    servicer.pop,
                    request_deserializer=queue__pb2.EmptyMessage.FromString,
                    response_serializer=queue__pb2.MessageResponse.SerializeToString,
            ),
            'size': grpc.unary_unary_rpc_method_handler(
                    servicer.size,
                    request_deserializer=queue__pb2.EmptyMessage.FromString,
                    response_serializer=queue__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/put',
            queue__pb2.Message.SerializeToString,
            queue__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def peek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/peek',
            queue__pb2.EmptyMessage.SerializeToString,
            queue__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/pop',
            queue__pb2.EmptyMessage.SerializeToString,
            queue__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def size(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/size',
            queue__pb2.EmptyMessage.SerializeToString,
            queue__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
